server:
  port: 8090
spring:
  datasource:
    username: root
    password: Hb3200
    url: jdbc:mysql://101.43.148.140:3306/wiki?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://121.196.19.146:3306/wiki?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 101.43.148.140
    port: 6379
    password: abc123456
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration: #sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    com:
      mapper: trace


# 通用 Mapper 配置
mapper:
  mappers: com.config.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL




